# Default values for simple_chart_gin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
autoMaxReplicas: 3
autoMinReplicas: 1
resourceName: cpu
Treshold: "70"


image:
  repository: asia.gcr.io/polar-cargo-139301/simple_gin
  tag: v1.0
  pullPolicy: Always

spec:
  containerPort: 8080


livenessProbe:
  httpGet:
    path: /trivia
readlinessProbe:
  httpGet:
    path: /trivia

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - simple_gin.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
